version: '3'

services:
  postgres:
    image: postgres:15.1-alpine
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=inservices
      - POSTGRES_PASSWORD=inservices
      - POSTGRES_DB=inservices
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    container_name: inservices_back
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://inservices:inservices@postgres:5432/inservices
    command: command: bash -c "pipenv run python manage.py migrate && pipenv run python manage.py collectstatic --noinput && pipenv run gunicorn resa.wsgi -b 0.0.0.0:8000 --log-file -"

volumes:
  pg_data:
