version: '3.8'
name: "inservices"
services:
  postgres:
    image: postgres:15.1-alpine
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=inservice
      - POSTGRES_PASSWORD=inservice
      - POSTGRES_DB=inservice
    ports:
      - "5432:5432"

  backend:
    container_name: inservices_back
    build: ./backend/
    depends_on:
      - postgres
    expose: 
      - "3000"
    command:
      - ./app
#      - -prod

  frontend:
    container_name: inservices_nginx_front
    build: ./frontend/
    ports:
      - "80:80"
volumes:
  pg_data:
